Grain/Grain/urls.py
from django.contrib import admin
from admins import views as admins
from django.urls import path
from users import views as usr
from . import views as mainView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainView.index, name='index'),
    path("UserRegister/", mainView.UserRegister, name="UserRegister"),
    path("AdminLogin/", mainView.AdminLogin, name="AdminLogin"),
    path('index/', mainView.index, name='index'), 
    path("UserLogin/", mainView.UserLogin, name="UserLogin"),

    ### User Side Views
    path("UserRegisterActions/", usr.UserRegisterActions, name="UserRegisterActions"),
    path("UserLoginCheck/", usr.UserLoginCheck, name="UserLoginCheck"),
    path("UserHome/", usr.UserHome, name="UserHome"),
    path("ViewData/", usr.ViewData, name="ViewData"),


    ### Admin Side Views
    path("AdminLoginCheck/", admins.AdminLoginCheck, name="AdminLoginCheck"),
    path("AdminHome/", admins.AdminHome, name="AdminHome"),
    path("ViewRegisteredUsers/", admins.ViewRegisteredUsers, name="ViewRegisteredUsers"),
    path("AdminActivaUsers/", admins.AdminActivaUsers, name="AdminActivaUsers"),
    # path("AdminDataPreProcess/", admins.AdminDataPreProcess, name="AdminDataPreProcess"),
    path("SVR/", usr.SVR, name = 'SVR'),
    path("RandomForest/", usr.RandomForest, name = 'RandomForest'),
    path("GradientBoosting/", usr.GradientBoosting, name= 'GradientBoosting'),
    path("GRSVR/", usr.GRSVR, name= 'GRSVR'),
    
]

Grain/users/forms.py
from django import forms
from .models import UserRegistrationModel


class UserRegistrationForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'pattern': '[a-zA-Z]+', 'class': 'form-control'}),
                           required=True, max_length=100)

    loginid = forms.CharField(widget=forms.TextInput(attrs={'pattern': '[a-zA-Z]+', 'class': 'form-control'}),
                              required=True, max_length=100)

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'pattern': '(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}', 'class': 'form-control',
                                          'title': 'Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters'}),
        required=True, max_length=100)

    mobile = forms.CharField(widget=forms.TextInput(attrs={'pattern': '[56789][0-9]{9}', 'class': 'form-control'}),
                             required=True,
                             max_length=100)

    email = forms.CharField(
        widget=forms.TextInput(attrs={'pattern': '[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$', 'class': 'form-control'}),
        required=True, max_length=100)

    locality = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, max_length=100)

    address = forms.CharField(widget=forms.Textarea(attrs={'rows': 3, 'cols': 20, 'class': 'form-control'}),
                              required=True, max_length=250)

    city = forms.CharField(widget=forms.TextInput(
        attrs={'autocomplete': 'off', 'pattern': '[A-Za-z ]+', 'title': 'Enter Characters Only ',
               'class': 'form-control'}), required=True,
        max_length=100)

    state = forms.CharField(widget=forms.TextInput(
        attrs={'autocomplete': 'off', 'pattern': '[A-Za-z ]+', 'title': 'Enter Characters Only ',
               'class': 'form-control'}), required=True,
        max_length=100)

    status = forms.CharField(widget=forms.HiddenInput(), initial='waiting', max_length=100)

    class Meta():
        model = UserRegistrationModel
        fields = '__all__'

Grain/assets/templates/AdminLogin.html
{% extends  'base.html' %}
{% load static %}

{% block title %}
    Admin Login
{% endblock %}
{% block admin_login %}
    active
{% endblock %}


{% block content %}
    <style>
        .jumbotron {
            font-family: "Book Antiqua";
            background: white;
            margin-top: 100px;
        }

        input[type=text] {
            padding: 1rem;
            width: 21rem;
        }

        input[type=password] {
            padding: 0.5rem;
            width: 20rem;
        }


    </style>

    <div class="jumbotron">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <h1 class="text-center p-2">Admin Login</h1> <br>

                    <form action="{% url 'AdminLoginCheck' %}" method="POST" class="text-primary" align="center">
                        {% csrf_token %}

                        <div class="form-group row">
                            <div class="col-md-12">
                                <input type="text" class="form-control" name="loginid" required
                                       placeholder="Enter Login Id">
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-12">
                                <input type="password" class="form-control" name="pswd" required
                                       placeholder="Enter password">
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-12">
                                <br>
                                <center>
                                    <input type="submit" style="width: 10%; padding: 9px;"> &nbsp;
                                    <input type="reset" style="width: 10%; padding: 10px; margin-top: -22px">
                                </center>
                            </div>
                        </div>


                        <!-- Message -->
                        {% if messages %}
                            {% for message in messages %}
                                <p align="center" class="text-primary"> {{ message }}</p>
                            {% endfor %}
                        {% endif %}


                    </form>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

Grain/assets/templates/UserLogin.html
{% extends 'base.html' %}
{% load static %}

{% block title %}User Login{% endblock %}
{% block user_login %}active{% endblock %}

{% block content %}
    <style>
        .jumbotron {
            font-family: "Book Antiqua";
            background: white;
            margin-top: 100px;
        }

        input[type=text] {
            padding: 1rem;
            width: 21rem;
        }

        input[type=password] {
            padding: 0.5rem;
            width: 20rem;
        }


    </style>

    <div class="jumbotron">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <h1 class="text-center p-2">User Login</h1> <br>
                    <form action="{% url 'UserLoginCheck' %}" method="POST" class="text-primary" align="center">
                        {% csrf_token %}

                        <div class="form-group row">
                            <div class="col-md-12">
                                <input type="text" class="form-control" name="loginname" required
                                       placeholder="Enter Login Id">
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-12">
                                <input type="password" class="form-control" name="pswd" required
                                       placeholder="Enter password">
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-12">
                                <br>
                                <center>
                                    <input type="submit" style="width: 10%; padding: 9px;"> &nbsp;
                                    <input type="reset" style="width: 10%; padding: 10px; margin-top: -22px">
                                </center>
                            </div>
                        </div>


                        <!-- Message -->
                        {% if messages %}
                            {% for message in messages %}
                                <p align="center" class="text-primary"> {{ message }}</p>
                            {% endfor %}
                        {% endif %}

                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Grain/assets/templates/UserRegistrations.html
{% extends 'base.html' %}
{% load static %}



{% block content %}

    <style>
        input[type=reset] {
            padding: 9px;
            margin-top: -25px;
        }

        input[type=reset]:hover {
            background-color: red;
            border-color: red;
            border-radius: 5px;
            padding: 9px;
            margin-top: -25px;
            color: whitesmoke;

        }

        input[type=text] {
            padding: 1rem;
            width: 40%;
        }

        input[type=password] {
            width: 38.5%;
            padding: 0.5rem;
        }

        input[type=submit]:hover {
            background: #f0bf00;
            border-color: #f0bf00;
            border-radius: 5px;
            color: whitesmoke;
        }
    </style>


    <!--form -->

    <div class="jumbotron">

        <div class="container">

            <div class="row" style="margin-top:1.5rem;">

                <form style="margin-left: 300px;width: 120%;" action="{% url 'UserRegisterActions' %}" method="POST">
                    {% csrf_token %}
                    <legend><em>User SignUp Form</em></legend>
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label for="id_name">User Name</label>

                            {{ form.name }}
                        </div>


                        <div class="form-group col-md-4">
                            <label for="id_loginid">Login Id</label>
                            {{ form.loginid }}
                        </div>


                        <div class="form-group col-md-4">
                            <label for="id_email">Email</label>
                            {{ form.email }}
                        </div>

                        <div class="form-group col-md-4">
                            <label for="id_mobile">Mobile</label>
                            {{ form.mobile }}
                        </div>


                        <div class="form-group col-md-4">
                            <label for="id_password">Password</label>
                            {{ form.password }}
                        </div>


                        <div class="form-group col-md-4">
                            <label for="id_locality">Locality</label>
                            {{ form.locality }}
                        </div>

                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label for="id_city">City</label>
                            {{ form.city }}
                        </div>

                        <div class="form-group col-md-4">

                        </div>
                        <div class="form-group col-md-4">
                            <label for="id_state">State</label>
                            {{ form.state }}
                        </div>
                        <div class="form-group col-md-2">
                            {#                            <label for="id_status">Status</label>#}
                            {{ form.status }}
                        </div>


                        <div class="form-group col-md-8" style="width: 40%">&nbsp;
                            <label for="id_address">Address </label>
                            {{ form.address }}

                        </div>


                    </div>

                    <div style="margin-left: 10%">
                        <input type="submit" style="width: 10%;" value="Register">
                        <input type="reset" style="width: 10%;" value="Reset">
                    </div>
                    <!-- Message -->
                    {% if messages %}
                        {% for message in messages %}
                            <p align="center" class="text-primary"> {{ message }}</p>
                        {% endfor %}
                    {% endif %}

                </form>

            </div>

        </div>

    </div>

{% endblock %}

Grain/assets/templates/base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">
<head>
    <title>GrainPrediction</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static  'css/style.css' %}" rel="stylesheet">
    <link rel='stylesheet' id='prettyphoto-css' href="{% static 'css/prettyPhoto.css' %}" type='text/css' media='all'>
    <link href="{% static  'css/fontello.css' %}" type="text/css" rel="stylesheet">
    <!--[if lt IE 7]>
<link href="css/fontello-ie7.css" type="text/css" rel="stylesheet">
<![endif]-->
    <link href='http://fonts.googleapis.com/css?family=Quattrocento:400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Patua+One' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <style type="text/css">
        body {
            padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
        }


    </style>
    <link href="{% static 'css/bootstrap-responsive.css' %}" rel="stylesheet">
    <!--[if lt IE 9]>
<script src="js/html5.js"></script>
<![endif]-->
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/jquery.scrollTo-1.4.2-min.js' %}"></script>
    <script src="{% static 'js/jquery.localscroll-1.2.7-min.js' %}"></script>
    <script charset="utf-8">
        $(document).ready(function () {
            $("a[rel^='prettyPhoto']").prettyPhoto();
        });
    </script>
</head>
<body>
<div class="navbar-wrapper">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container"><a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span
                    class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </a>
                <h1 class="brand"><a href="/">Grain!</a></h1>
                <nav class="pull-right nav-collapse collapse">
                    <ul id="menu-main" class="nav">
                        <li><a title="portfolio" href="{% url 'index' %}">Home</a></li>
                        <li><a title="news" href="{% url 'UserLogin' %}">User</a></li>
                        <li><a title="team" href="{% url 'AdminLogin' %}">Admin</a></li>
                        <li><a title="contact" href="{% url 'UserRegister' %}">Sign Up</a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</div>
<div id="top"></div>






{% block content %}

{% endblock %}
<hr style="  border: 5px solid #f0bf00;">
<div class="footer-wrapper">
    <div class="container">
        <footer>
            <p style="margin-top:-10px ;">&copy; 2021 <a>Alex Corporation</a>. All rights reserved.</p>

        </footer>
    </div>
</div>
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
<script src="{% static 'js/site.js' %}"></script>
</body>
</html>